# Generated by Django 5.0.2 on 2025-06-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="analysisreport",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analysis_reports",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="codequalitymetric",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projectfile"
            ),
        ),
        migrations.AddField(
            model_name="codequalitymetric",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quality_metrics",
                to="analysis.analysisreport",
            ),
        ),
        migrations.AddField(
            model_name="performancemetric",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_metrics",
                to="analysis.analysisreport",
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projectfile"
            ),
        ),
        migrations.AddField(
            model_name="securityissue",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_issues",
                to="analysis.analysisreport",
            ),
        ),
        migrations.AddField(
            model_name="testcoverage",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="projects.projectfile"
            ),
        ),
        migrations.AddField(
            model_name="testcoverage",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_coverage",
                to="analysis.analysisreport",
            ),
        ),
    ]
